### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by cprdana** [cyrillbolliger/conditional-featured-image#28] opened 2022-02-09 15:02 UTC
After updating to the latest version of Wordpress (5.9), the "conditionally feature image..." plugin stopped working. Posts previously set with the plugin selected are still presenting properly. However, when adding new posts, we are no longer able to save the post with the "Conditionally display featured image" box checked.

**Comment by cyrillbolliger** [comment] 2022-05-08 15:13
Duplicate of https://wordpress.org/support/topic/display-featured-image-not-working/

**Closed by cyrillbolliger** 2022-05-08 15:13 UTC
